routes:
  - name: completions
    route_type: llm/v1/completions
    model:
      provider: bedrock
      name: anthropic.claude-v2
      config:
        aws_config:
          aws_region: $AWS_BEDROCK_REGION